version: '2.3'

services:
  tendermint_this:
    image: tendermint/tendermint:0.22.4
    ports:
      - "26656:26656"
      - "127.0.0.1:26657:26657"
    restart: always
    entrypoint: ''
    command: sh -c "tendermint node --consensus.create_empty_blocks=false --proxy_app=tcp://bigchaindb_this:26658 --p2p.persistent_peers=$PEERS --log_level=*:info"
    volumes:
      - ./tmdata/$NET_NAME/this/config:/tendermint/config
      - ./docker/volumes/$NET_NAME/tendermint/$NET_NAME/this/data:/tendermint/data
#    links:
#      - tendermint_node0
#      - tendermint_node1
#      - tendermint_node2
#      - tendermint_node3


  mongodb_this:
    image: mongo:3.7
    ports:
      - "127.0.0.1:27017:27017/tcp"
    volumes:
      - ./docker/volumes/$NET_NAME/mono/this:/data/db
    restart: always


  bigchaindb_this:
    image: bigchaindb/bigchaindb:2.0.0-beta3
    depends_on:
      - mongodb_this
      - tendermint_this
    links:
      - mongodb_this:mongodb
      - tendermint_this:tendermint
    environment:
      BIGCHAINDB_DATABASE_BACKEND: localmongodb
      BIGCHAINDB_DATABASE_HOST: mongodb
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_WSSERVER_ADVERTISED_HOST: bigchaindb
      BIGCHAINDB_TENDERMINT_HOST: tendermint
      BIGCHAINDB_TENDERMINT_PORT: 26657
    ports:
      - "127.0.0.1:9984:9984"
      - "127.0.0.1:9985:9985"
      - "127.0.0.1:26658:26658"
    volumes:
      - ./docker/volumes/$NET_NAME/bigchaindb/this/data:/data
      - ./docker/volumes/$NET_NAME/bigchaindb/this/certs:/certs
    healthcheck:
      test: ["CMD", "bash", "-c", "curl http://bigchaindb_this:9984 && curl http://tendermint:26657/abci_query"]
      interval: 3s
      timeout: 5s
      retries: 3
    entrypoint: sh -c "bigchaindb -l INFO -y configure && bigchaindb -l DEBUG start"
    restart: always

  ipfs:
    image: ipfs/go-ipfs:v0.4.17
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
    restart: always


volumes:
  ipfs_staging:
    driver: local
  ipfs_data:
    driver: local

