version: '2.3'

services:
  producer:
    image: tataucloud/core_cpu
    command: sh -c "python producer.py"
    environment:
      RING: $RING
      TATAU_DEBUG: $TATAU_DEBUG
      TATAU_RAVEN_DSN: $TATAU_RAVEN_DSN
      KEYS_ROOT: $KEYS_ROOT
      POA_NET: $POA_NET
      PRODUCER_ACCOUNT_ADDRESS: $PRODUCER_ACCOUNT_ADDRESS
    volumes:
      - $PWD/$KEYS_ROOT/$POA_NET/$PRODUCER_ACCOUNT_ADDRESS:/app/$KEYS_ROOT/$POA_NET/$PRODUCER_ACCOUNT_ADDRESS:ro
      - $PWD/$KEYS_ROOT/$POA_NET/whitelist.json:/app/$KEYS_ROOT/$POA_NET/whitelist.json:ro
    restart: always
    links:
      - ipfs
      - bigchaindb_this:bigchaindb
      - mongodb_this:mongodb
      - tendermint_this:tendermint
      - parity
