version: '2.3'

services:
  producer:
    image: tataucloud/core_cpu
    command: sh -c "python producer.py"
    environment:
      RING: $RING
      TATAU_DEBUG: $TATAU_DEBUG
      TATAU_RAVEN_DSN: $TATAU_RAVEN_DSN
      KEYS_ROOT: $KEYS_ROOT
      NET: $NET
      PRODUCER_ACCOUNT_ADDRESS: $PRODUCER_ACCOUNT_ADDRESS
    volumes:
      - $PWD/$KEYS_ROOT/$NET/$PRODUCER_ACCOUNT_ADDRESS:/app/$KEYS_ROOT/$NET/$PRODUCER_ACCOUNT_ADDRESS:ro
      - $PWD/$KEYS_ROOT/$NET/whitelist.json:/app/$KEYS_ROOT/$NET/whitelist.json:ro
    restart: always
    links:
      - ipfs
      - bigchaindb
      - mongodb
      - tendermint
      - parity
