version: '2.3'

services:
  producer:
    image: tataucloud/core_cpu
    command: sh -c "python producer-no-socket.py"
    environment:
      RING: $RING
      TATAU_DEBUG: $TATAU_DEBUG
      TATAU_RAVEN_DSN: $TATAU_RAVEN_DSN
      KEYS_PATH: $KEYS_PATH
      PRODUCER_ACCOUNT_ADDRESS: $PRODUCER_ACCOUNT_ADDRESS
    volumes:
      - $PWD/$KEYS_PATH/$PRODUCER_ACCOUNT_ADDRESS:/app/$KEYS_PATH/$PRODUCER_ACCOUNT_ADDRESS:ro
    restart: always
    links:
      - ipfs
      - bigchaindb_this:bigchaindb
      - mongodb_this:mongodb
      - tendermint_this:tendermint
      - parity
