version: '3'

services:
  verifier:
    image: tataucloud/core_cpu
    build:
      context: .
      dockerfile: ./docker/images/core/cpu/Dockerfile
    command: sh -c "env && python verifier.py"
    env_file:
      - $PWD/docker/.env
    volumes:
      - $PWD/keys:/app/keys
    restart: always
    links:
      - ipfs
      - bigchaindb_this:bigchaindb
      - mongodb_this:mongodb
      - tendermint_this:tendermint
