version: '2.3'

services:
  verifier:
    image: tataucloud/verifier
    build:
      context: .
      dockerfile: ./docker/images/verifier/Dockerfile
    command: sh -c "python verifier.py"
    # Support nvidia docker 2
    runtime: nvidia
    volumes:
      - ./verifier:/app/verifier:ro
      - $PWD/$KEYS_ROOT/$NET/$VERIFIER_ACCOUNT_ADDRESS:/app/$KEYS_ROOT/$NET/$VERIFIER_ACCOUNT_ADDRESS:ro
    restart: always
    links:
      - ipfs
      - bigchaindb
      - mongodb
      - tendermint
      - parity
    shm_size: '4gb'
    environment:
      RING: $RING
      TATAU_DEBUG: $TATAU_DEBUG
      TATAU_RAVEN_DSN: $TATAU_RAVEN_DSN
      KEYS_ROOT: $KEYS_ROOT
      VERIFIER_ACCOUNT_ADDRESS: $VERIFIER_ACCOUNT_ADDRESS
      NET: $NET