version: '2.3'

services:
  verifier:
    image: tataucloud/verifier
    build:
      context: .
      dockerfile: ./docker/images/verifier/Dockerfile
    command: sh -c "python verifier-no-socket.py"
    # Support nvidia docker 2
    runtime: nvidia
    volumes:
      - PWD/verifier:/app/verifier:ro
      - $PWD/$KEYS_PATH/$VERIFIER_ACCOUNT_ADDRESS:/app/$KEYS_PATH/$VERIFIER_ACCOUNT_ADDRESS:ro
    restart: always
    links:
      - ipfs
      - bigchaindb_this:bigchaindb
      - mongodb_this:mongodb
      - tendermint_this:tendermint
      - parity
    environment:
      RING: $RING
      TATAU_DEBUG: $TATAU_DEBUG
      TATAU_RAVEN_DSN: $TATAU_RAVEN_DSN
      KEYS_PATH: $KEYS_PATH
      VERIFIER_ACCOUNT_ADDRESS: $VERIFIER_ACCOUNT_ADDRESS