version: '2.3'

services:
  worker_gpu:
    image: tataucloud/core_gpu
    build:
      context: .
      dockerfile: ./docker/images/core/gpu/Dockerfile
    command: sh -c "python worker-no-socket.py"
    # Support nvidia docker 2
    runtime: nvidia
    volumes:
      - $PWD/$KEYS_ROOT/$POA_NET/$WORKER_ACCOUNT_ADDRESS:/app/$KEYS_ROOT/$POA_NET/$WORKER_ACCOUNT_ADDRESS:ro
    restart: always
    links:
      - ipfs
      - bigchaindb_this:bigchaindb
      - mongodb_this:mongodb
      - tendermint_this:tendermint
      - parity
    environment:
      RING: $RING
      TATAU_DEBUG: $TATAU_DEBUG
      TATAU_RAVEN_DSN: $TATAU_RAVEN_DSN
      KEYS_ROOT: $KEYS_ROOT
      WORKER_ACCOUNT_ADDRESS: $WORKER_ACCOUNT_ADDRESS
