version: '2.3'

services:
  worker_cpu:
    image: tataucloud/core_cpu
    build:
      context: .
      dockerfile: ./docker/images/core/cpu/Dockerfile
    command: sh -c "python worker.py"
    volumes:
      - $PWD/$KEYS_ROOT/$POA_NET/$WORKER_ACCOUNT_ADDRESS:/app/$KEYS_ROOT/$POA_NET/$WORKER_ACCOUNT_ADDRESS:ro
    restart: always
    links:
      - ipfs
      - bigchaindb
      - mongodb
      - tendermint
      - parity
    environment:
      RING: $RING
      TATAU_DEBUG: $TATAU_DEBUG
      TATAU_RAVEN_DSN: $TATAU_RAVEN_DSN
      KEYS_ROOT: $KEYS_ROOT
      WORKER_ACCOUNT_ADDRESS: $WORKER_ACCOUNT_ADDRESS
