version: '2.3'

services:
  worker:
    image: tataucloud/core_cpu
    build:
      context: .
      dockerfile: ./docker/images/core/cpu/Dockerfile
    command: sh -c "python worker-no-socket.py"
    volumes:
      - ./keys/${RING}:/app/keys
    restart: always
    links:
      - ipfs
      - bigchaindb_this:bigchaindb
      - mongodb_this:mongodb
      - tendermint_this:tendermint
    environment:
      RING: $RING
      TATAU_DEBUG: $TATAU_DEBUG
      TATAU_RAVEN_DSN: $TATAU_RAVEN_DSN
      TATAU_DBD_HOST: bigchaindb
      TATAU_MONGO_DB_HOST: mongodb
      TATAU_MONGO_DB_PORT: 27017
      TATAU_IPFS_HOST: ipfs
      TATAU_IPFS_PORT: 5001
