version: '2.3'

services:
  worker_cpu:
    image: tataucloud/core_cpu
    build:
      context: .
      dockerfile: ./docker/images/core/cpu/Dockerfile
    command: sh -c "python worker-no-socket.py"
    volumes:
      - ./keys/${RING}:/app/keys
    restart: always
    links:
      - ipfs
      - bigchaindb_this:bigchaindb
      - mongodb_this:mongodb
      - tendermint_this:tendermint
      - parity
    environment:
      RING: $RING
      TATAU_DEBUG: $TATAU_DEBUG
      TATAU_RAVEN_DSN: $TATAU_RAVEN_DSN
      CONTRACT_ADDRESS: $CONTRACT_ADDRESS
      TFLOPS_COST: $TFLOPS_COST
      ACCOUNT_ADDRESS: $ACCOUNT_ADDRESS
