version: '2.3'

services:
  worker_gpu:
    image: tataucloud/core_gpu
    build:
      context: .
      dockerfile: ./docker/images/core/gpu/Dockerfile
    command: sh -c "python worker.py"
    # Support nvidia docker 2
    runtime: nvidia
    volumes:
      - $PWD/$KEYS_ROOT/$NET/$WORKER_ACCOUNT_ADDRESS:/app/$KEYS_ROOT/$NET/$WORKER_ACCOUNT_ADDRESS:ro
    restart: always
    links:
      - ipfs
      - bigchaindb
      - mongodb
      - tendermint
      - parity
    shm_size: '4gb'
    environment:
      RING: $RING
      TATAU_DEBUG: $TATAU_DEBUG
      TATAU_RAVEN_DSN: $TATAU_RAVEN_DSN
      KEYS_ROOT: $KEYS_ROOT
      WORKER_ACCOUNT_ADDRESS: $WORKER_ACCOUNT_ADDRESS
      NET: $NET
